version: "3.9"
services:
  anonygram:
    image: alan10607/anonygram:latest
    container_name: anonygram
    ports:
     - "443:443"
    volumes:
     - "~/docker/volume/anonygram/log:/log"
    environment:
     - ACTIVE=prod
    depends_on:
     - ag-mysql
     - ag-redis
    networks:
     - proxy
    command: ["/wait-for-it.sh", "ag-mysql:3306", "--", "/wait-for-it.sh", "ag-redis:6379", "--", "java","-jar","/anonygram.jar"]

  ag-mysql:
    image: mysql:8.0.30
    container_name: ag-mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=ag
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - proxy

  ag-redis:
    image: redis:7.0.4
    container_name: ag-redis
    ports:
      - "6380:6379"
    volumes:
      - "~/docker/volume/redis/data:/data"
      - "~/docker/volume/redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "~/docker/volume/redis/logs:/logs"
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes --requirepass "root"
    networks:
      - proxy

networks:
  proxy:
    name: ag-network
