spring:
  cors:
    frontend: http://localhost:3000

logging:
  path: /log

imgur:
  clientId: 290ef3ac4c1f094
  clientSecret: 9892fb9143cb70aee0b1c1879de3cbb0d9742917
  albumId: hpyaPc6

elasticsearch:
  host: ${ES_HOST:localhost}
  port: 9200
  username: elastic
  password: root
