spring:
  cors:
    frontend: https://alan10607.github.io/

logging:
  path: /log

imgur:
  clientId: eded92adbc0fab0
  clientSecret: df9529b0b964bcede52760d688e4c57190a8842f
  albumId: WcBFFA5

elasticsearch:
  host: localhost
  port: 9200
  username: elastic
  password: OGmrJovJi37nakTDF*zc
